### ISSUE TITLE
Curly braces would have been nice 😉

### ISSUE THREAD

**Issue by markusdosch** [d-emrani/finite-state-machine#2]
see https://stackoverflow.com/a/2125078

### Examples

https://github.com/d-emrani/finite-state-machine/blob/6241263e7b25eefea5a68b62394ef84ddf3bc49d/src/FiniteStateMachine.java#L31-L36

https://github.com/d-emrani/finite-state-machine/blob/6241263e7b25eefea5a68b62394ef84ddf3bc49d/src/FiniteStateMachine.java#L58-L61

**Comment by d-emrani** [comment]
Fixed!
